Resources:
  FrontendAccomodationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.environment.BUCKET_NAME}
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendAccomodationBucketRootConfigS3AccessPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: S3OriginAccessIdentity
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource:
              Fn::Join:
                - ''
                - 
                  - Fn::GetAtt: [FrontendAccomodationBucket, Arn]
                  - '/*'
      Bucket:
        Ref: FrontendAccomodationBucket